### ISSUE TITLE
Candidate: Hard-reload deeplink to candidate

### ISSUE THREAD

**Issue by rakeden** [wax-office-of-inspector-general/oig.wax.io#27]
When opening the candidate card from a deeplink the candidate modal is not displayed correctly.
It seems that the modal is under the navigation and the backdrop doesn't appear.

We need to fix that, but it's not the most urgent issue

**Comment by AlexandreSSJr** [comment]
Fixed by https://github.com/wax-office-of-inspector-general/oig.wax.io/pull/35

**Comment by rakeden** [comment]
Nice!
